development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: ontabV1_development
  pool: 5
  username: ontab_local
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: ontabV1_test
  pool: 5
  username: ontab_local
  password:


